{
 "title": "Energie Landkreis Lüneburg",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Erzeugung",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "usage{name=\"wind\",type=\"feed_in\"}*4",
     "legendFormat": "Windkraft"
    },
    {
     "expr": "usage{name=\"solar\",type=\"feed_in\"}*4",
     "legendFormat": "Photovoltaik"
    },
    {
     "expr": "usage{name=\"bio\",type=\"feed_in\"}*4",
     "legendFormat": "Biomasse"
    },
    {
     "expr": "usage{name=\"water\",type=\"feed_in\"}*4",
     "legendFormat": "Wasserkraft"
    },
    {
     "expr": "usage{name=\"others\",type=\"feed_in\"}*4",
     "legendFormat": "Weitere Erzeuger"
    },
    {
     "expr": "sum(usage{type=\"feed_in\"})*4",
     "legendFormat": "Gesamtleistung (lokal)"
    },
    {
     "expr": "clamp_min((sum(usage{type=\"consumption\"})-sum(usage{type=\"feed_in\"}))*4,0)",
     "legendFormat": "Netzbezug"
    }
   ]
  },
  {
   "title": "Verbrauch",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "usage{name=\"domestic\",type=\"consumption\"}*4",
     "legendFormat": "Private Haushalte"
    },
    {
     "expr": "usage{name=\"industrial\",type=\"consumption\"}*4",
     "legendFormat": "Industrie und Gewerbe"
    },
    {
     "expr": "usage{name=\"public\",type=\"consumption\"}*4",
     "legendFormat": "Kommunale Anlagen"
    },
    {
     "expr": "sum(usage{type=\"consumption\"})*4",
     "legendFormat": "Gesamtleistung (lokal)"
    },
    {
     "expr": "clamp_min((sum(usage{type=\"feed_in\"})-sum(usage{type=\"consumption\"}))*4,0)",
     "legendFormat": "Netzeinspeisung"
    }
   ]
  },
  {
   "title": "Erzeugung",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    {
     "expr": "usage{type=\"feed_in\", name=\"others\"}*4",
     "legendFormat": "Weitere Erzeuger"
    },
    {
     "expr": "usage{type=\"feed_in\", name=\"water\"}*4",
     "legendFormat": "Wasserkraft"
    },
    {
     "expr": "usage{type=\"feed_in\", name=\"bio\"}*4",
     "legendFormat": "Biomasse"
    },
    {
     "expr": "usage{type=\"feed_in\", name=\"solar\"}*4",
     "legendFormat": "Photovoltaik"
    },
    {
     "expr": "usage{type=\"feed_in\", name=\"wind\"}*4",
     "legendFormat": "Windkraft"
    }
   ]
  },
  {
   "title": "Verbrauch",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    {
     "expr": "usage{type=\"consumption\",name=\"public\"}*4",
     "legendFormat": "Kommunale Anlagen"
    },
    {
     "expr": "usage{type=\"consumption\",name=\"industrial\"}*4",
     "legendFormat": "Industrie und Gewerbe"
    },
    {
     "expr": "usage{type=\"consumption\",name=\"domestic\"}*4",
     "legendFormat": "Private Haushalte"
    }
   ]
  },
  {
   "title": "Windenergie",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    {
     "expr": "usage{type=\"feed_in\",name=\"wind\"}*4",
     "legendFormat": "Leistung"
    },
    {
     "expr": "installed_capacity{type=\"feed_in\",name=\"wind\"}",
     "legendFormat": "Gesamtkapazität"
    }
   ]
  },
  {
   "title": "Photovoltaik",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    {
     "expr": "usage{type=\"feed_in\",name=\"solar\"}*4",
     "legendFormat": "Leistung"
    },
    {
     "expr": "installed_capacity{type=\"feed_in\",name=\"solar\"}",
     "legendFormat": "Gesamtkapazität"
    }
   ]
  },
  {
   "title": "Biomasse",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    {
     "expr": "usage{type=\"feed_in\",name=\"bio\"}*4",
     "legendFormat": "Leistung"
    },
    {
     "expr": "installed_capacity{type=\"feed_in\",name=\"bio\"}",
     "legendFormat": "Gesamtkapazität"
    }
   ]
  },
  {
   "title": "Wasserkraft",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    {
     "expr": "usage{type=\"feed_in\",name=\"water\"}*4",
     "legendFormat": "Leistung"
    },
    {
     "expr": "installed_capacity{type=\"feed_in\",name=\"water\"}",
     "legendFormat": "Gesamtkapazität"
    }
   ]
  },
  {
   "title": "Weitere Erzeuger",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    {
     "expr": "usage{type=\"feed_in\",name=\"others\"}*4",
     "legendFormat": "Leistung"
    },
    {
     "expr": "installed_capacity{type=\"feed_in\",name=\"others\"}",
     "legendFormat": "Gesamtkapazität"
    }
   ]
  },
  {
   "title": "Autarkie",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "autarky", "legendFormat": "Autarkie" }
   ]
  },
  {
   "title": "Netzbezug",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    {
     "expr": "(sum(usage{type=\"consumption\"})-sum(usage{type=\"feed_in\"}))*4",
     "legendFormat": "Leistung"
    }
   ]
  }
 ]
}